[workspace]
members = [
    "bins/cli",
    "bins/driver",
    "crates/core",
    "crates/shared",
]
resolver = "2"

[workspace.dependencies]
ffmpeg-next = "8.0.0"
mlua = "0.11.5"
sdl2 = "0.38.0"
skia-safe = "0.91.1"