[package]
name = "hoshimi_ui"
version = { workspace = true}
edition = { workspace = true}

[dependencies]
hoshimi_shared = { path = "../shared" }
hoshimi_renderer = { path = "../renderer" }
tracing = { workspace = true }
