[package]
name = "hoshimi_renderer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
hoshimi_shared = { path = "../shared", features = ["skia"] }
skia-safe = { workspace = true }