[package]
name = "hoshimi_renderer"
version = { workspace = true}
edition = { workspace = true}

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
hoshimi_shared = { path = "../shared", features = ["skia"] }
skia-safe = { workspace = true }