[package]
name = "hoshimi_types"
version = { workspace = true}
edition = { workspace = true}

[features]
default = []
skia = ["dep:skia-safe"]

[dependencies]
skia-safe = { workspace = true, optional = true }