[package]
name = "hoshimi_shared"
version = { workspace = true}
edition = { workspace = true}

[features]
default = []
skia = ["dep:skia-safe"]

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
skia-safe = { workspace = true, optional = true }